### ISSUE TITLE
Crash calling exported function from host

### ISSUE THREAD

**Issue by TobyEalden** [coder-mike/microvium-ffi-example#1]
I've made a few tweaks to `ffi.js` and added a `main.cpp` to test the integration.

See https://github.com/TobyEalden/microvium-ffi-example/commit/50181868a597e535f4800d0020e15047c8ed4222

I've included the generated files in the commit for completeness, there is currently a crash at https://github.com/TobyEalden/microvium-ffi-example/blob/runnable-example/app_ffi.c#L89.

**Comment by TobyEalden** [comment]
It seems like there is a bug in the exportToC function, or in the subsequent snapshotting, in that the functions are getting optimised out of the final bytecode. If you examine the contents of `_vmExports[]` in `app_ffi.c`, the last 3 entries all have the same value.

Changing `mvm_newObject.js` to the following appears to fix the issue:

```js
import {exportToC} from './ffi.js';

function newObject() {
    return {};
}

function setProp(obj, key, value) {
    obj[key] = value;
}

function getProp(obj, key) {
    return obj[key];
}

exportToC('any', 'mvm_newObject', [], newObject);

exportToC('void', 'mvm_setProp', [['any', 'obj'], ['string', 'key'], ['any', 'value']], setProp);

exportToC('any', 'mvm_getProp', [['any', 'obj'], ['string', 'key']], getProp);
```

**Comment by coder-mike** [comment]
Ok, yes, I've confirmed the issue. When I run `microvium main.js --map-file main.map`, the resulting `main.map` has the following export table:

```
001e   10  - # Export Table
001e       4     [65535]: &0098
0022       4     [65534]: &00cc
0026       4     [65533]: &00cc
002a       4     [65532]: &00cc
```

(the left-hand column is the address in the bytecode image, and the right-hand column has the value, which in this case is a pointer to the address 0x00cc in the bytecode image)

So the last 3 entries are the same, as you observed at runtime. I suspect this is a bug in the snapshot encoding. I'll look into it.

**Comment by coder-mike** [comment]
Ok, there's something broken with arrow functions. If I change `mvm_newObject.js` to use function declarations then it works:

```js
import { exportToC } from './ffi.js';

function mvm_newObject() {
  return {}
}

function mvm_setProp(obj, key, val) {
  obj[key] = val
}

function mvm_getProp(obj, key) {
  return obj[key]
}

exportToC('any', 'mvm_newObject', [], mvm_newObject);

exportToC('void', 'mvm_setProp', [['any', 'obj'], ['string', 'key'], ['any', 'value']], mvm_setProp);

exportToC('any', 'mvm_getProp', [['any', 'obj'], ['string', 'key']], mvm_getProp);
```

I'll look into it.

**Comment by coder-mike** [comment]
Ok! Progress! Take a look at this...

```js
// main.js

const getResource = importFromC('any', 'getResource', [['string', 'name']]);

onRestore(() => {
  console.log('Starting!');
  console.log('Getting resource...')
  const res = getResource("@root");
  console.log(`The resource's name is "${res.name}"`)
});

generate();
```

```cpp
// main.cpp

#include <iostream>
#include "app_ffi.hpp"

using namespace std;
using namespace mvm;

const uint8_t snapshot[] = { ... };

int main(int argc, char** argv) {
    App app(snapshot, sizeof snapshot);
    return 0;
}

Any getResource(App& app, string name) {
    Any resource = app.newObject();
    app.setProp(resource, "name", app.newString("Toby"));
    return resource;
}

void print(App& app, string msg) { std::cout << msg << std::endl; }
```

Prints:

```
Starting!
Getting resource...
The resource's name is "Toby"
```

The full example is committed to `main` in this repo.

Please update Microvium to 0.0.24 to fix the issue with anonymous functions.

I ported the FFI to C++ so that I could take advantage of the RAII pattern to automatically interact with Handles, so you don't have to remember when to use a handle or not (see the implementation of [Any](https://github.com/coder-mike/microvium-ffi-example/blob/main/app_ffi.hpp#L17-L41))

@morganrallen You may also be interested in this update as it relates to [#40](https://github.com/coder-mike/microvium/issues/40) and [#41](https://github.com/coder-mike/microvium/issues/41)

**Comment by TobyEalden** [comment]
I can confirm this works a treat, many thanks!
